### PR TITLE
Add intro slides

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by sylee957** [comment]
How is the TeX built?

**Comment by asmeurer** [comment]
Use the makefile. But once it's finalized we should just commit the pdf so it's easy to load.

**Comment by asmeurer** [comment]
Here's the current version if you want to review. 
[intro.pdf](https://github.com/sympy/scipy-2023-tutorial/files/11923538/intro.pdf)

**Comment by sylee957** [comment]
I think that you should remove ‘geometric algebra’

**Pull request merged**
